---
- name: Baden-Württemberg
  abbr: BW
- name: Bayern
  abbr: BY
- name: Berlin
  abbr: BE
- name: Brandenburg
  abbr: BB
- name: Bremen
  abbr: HB
- name: Hamburg
  abbr: HH
- name: Hessen
  abbr: HE
- name: Mecklenburg-Vorpommern
  abbr: MV
- name: Niedersachsen
  abbr: NI
- name: Nordrhein-Westfalen
  abbr: NW
- name: Rheinland-Pfalz
  abbr: RP
- name: Saarland
  abbr: SL
- name: Sachsen
  abbr: SN
- name: Sachsen-Anhalt
  abbr: ST
- name: Schleswig-Holstein
  abbr: SH
- name: Thüringen
  abbr: TH
